#!/usr/bin/env bash
# Dockyard installer.
#
# Takes a fresh Linux host to a running panel: Docker Engine with the Compose plugin, git (the
# updater pulls the checkout, so the deployed directory has to be a clone), curl and openssl for the
# generated secrets, then the panel and its Postgres, then the host updater. It finishes by asking
# the panel whether it is up, so a green summary means the API answered, not that a command exited 0.
#
#   curl -fsSL https://raw.githubusercontent.com/dockyardapp/dockyard/main/install.sh | sudo bash
#
# or, from a checkout you already have:
#
#   sudo ./install.sh
#
# Re-running is safe. An existing checkout is reused, an existing .env is never rewritten, and the
# image is rebuilt from whatever the checkout holds.
#
# Flags:
#   --dir PATH          where to install (default: this checkout, else /opt/dockyard)
#   --port N            host port to publish the panel on (default 8000)
#   --bind ADDR         address to publish on (default 0.0.0.0; 127.0.0.1 keeps it on the host).
#                       With --proxy this is the address nginx publishes on, and the panel moves to
#                       127.0.0.1 either way, because nginx is meant to be the only public door.
#   --public-url URL    the URL the panel will be reached at, used for the links it shows
#   --email ADDR        admin account email (default admin@dockyard.local)
#   --password PASS     admin password (generated and shown once if you do not pass one)
#   --no-admin          leave the admin account unset and register it in the UI instead
#   --repo URL          repository to clone (default the public Dockyard repository)
#   --branch NAME       branch to install (default main)
#   --no-updater        skip the host updater; the Install update button stays disabled
#   --no-firewall       never touch the firewall, only report what it would need
#   --proxy             put nginx in front of the panel, so nginx is the only public door
#   --no-proxy          no nginx; the panel itself is the door (default)
#   --cert MODE         self-signed | letsencrypt | none (default: none, or self-signed with --proxy)
#   --domain NAME       the name or IP the panel is reached at, used for nginx and the certificate
#   --http-port N       nginx HTTP port (default 80)
#   --https-port N      nginx HTTPS port (default 443)
#   --tui               force the interactive setup even when it would not normally run
#   --no-tui            never run it; take the flags and the defaults as given
#   --dry-run           print what would happen and change nothing
#   -h, --help          this
#
# Run with no flags on a terminal and it walks you through the choices it cannot make for you: how
# the panel should be reached, whether nginx terminates TLS, what certificate to use, and which
# address to listen on. Passing any of --proxy, --cert, --domain, --bind or --email is taken as
# having answered, and the questions are skipped. Piped into bash with no terminal it stays
# non-interactive and uses the defaults, so `curl | bash` still installs unattended.
#
# Why nginx is off by default: it needs ports 80 and 443, and that is a decision about the host, not
# about the app. When it is on, the panel is republished on 127.0.0.1 so nginx is the only public
# door. That matters more than it sounds: the panel mounts the Docker socket, so its port is a
# root-equivalent door, and until now the installer published it on every interface with a plain
# HTTP session cookie.
#
# Why an admin password is generated by default: the panel mounts the Docker socket, so anyone who
# can sign in has root-equivalent control of the host. The user table is empty until an account
# exists, and while it is empty the bootstrap route is open, so an install published on a public
# address with no password set is a race that whoever finds the port first wins. Generating one
# closes that window. Pass --no-admin to take the race deliberately.
set -Eeuo pipefail

DEFAULT_REPO_URL="https://github.com/dockyardapp/dockyard.git"
DEFAULT_EMAIL="admin@dockyard.local"

INSTALL_DIR=""
PANEL_PORT="8000"
PANEL_BIND="0.0.0.0"
PUBLIC_URL=""
ADMIN_EMAIL="$DEFAULT_EMAIL"
ADMIN_PASSWORD=""
ADMIN_GENERATED="no"
REPO_URL="$DEFAULT_REPO_URL"
BRANCH="main"
INSTALL_UPDATER="yes"
SET_ADMIN="yes"
TOUCH_FIREWALL="yes"
DRY_RUN="no"

# --- the reverse proxy and the interactive setup ---
# PROXY_ENABLE is off by default because nginx wants ports 80 and 443, which is a decision about the
# host rather than about the app. CERT_MODE=none with PROXY_ENABLE=yes is a real combination: it is
# the "something else already terminates TLS" case, and also the plain-HTTP case behind a tunnel.
PROXY_ENABLE="no"
PROXY_BIND="0.0.0.0"
PROXY_HTTP_PORT="80"
PROXY_HTTPS_PORT="443"
CERT_MODE="none"
CERT_MODE_SET="no"
DOMAIN=""
TUI="auto"
# Set when a flag that answers one of the TUI's questions is seen, so the questions are not asked
# again. --dry-run counts: a dry run should not stop for input.
DECIDED="no"
# Narrower than DECIDED: whether the proxy itself was chosen. Only then are the proxy settings
# applied to an .env that already exists, so a run that never mentions nginx cannot disturb one.
PROXY_DECIDED="no"
# Whether --bind was given. With the proxy on, that address belongs to nginx rather than the panel,
# so it has to be told apart from the default.
BIND_SET="no"

COMPOSE=()

say()  { printf '  %s\n' "$*"; }
step() { printf '\n%s\n' "$*"; }
# Warnings go to stdout with the rest of the report, not to stderr. This script's output is a
# document a person reads top to bottom, and splitting it across two streams means `./install.sh |
# tee install.log` shows every warning before the step it belongs to.
warn() { printf '  ! %s\n' "$*"; }
die()  { printf '\n  x %s\n\n' "$*" >&2; exit 1; }

# Mutating commands go through these, so --dry-run has exactly one meaning: nothing changes.
run() {
  if [ "$DRY_RUN" = "yes" ]; then
    printf '  [dry-run] %s\n' "$*"
    return 0
  fi
  "$@"
}
run_sh() {
  if [ "$DRY_RUN" = "yes" ]; then
    printf '  [dry-run] sh -c %s\n' "$1"
    return 0
  fi
  sh -c "$1"
}

# For steps whose output is loud and uninteresting: a package manager unpacking a hundred
# dependencies buries the report this script exists to print. Capture it and surface it only when the
# step fails, so a failure is still fully explained.
run_quiet() {
  if [ "$DRY_RUN" = "yes" ]; then
    printf '  [dry-run] %s\n' "$*"
    return 0
  fi
  local log
  log="$(mktemp)"
  if "$@" >"$log" 2>&1; then
    rm -f "$log"
    return 0
  fi
  printf '  step failed: %s\n' "$*"
  sed 's/^/    /' "$log"
  rm -f "$log"
  return 1
}
run_quiet_sh() {
  if [ "$DRY_RUN" = "yes" ]; then
    printf '  [dry-run] sh -c %s\n' "$1"
    return 0
  fi
  local log
  log="$(mktemp)"
  if sh -c "$1" >"$log" 2>&1; then
    rm -f "$log"
    return 0
  fi
  printf '  step failed: sh -c %s\n' "$1"
  sed 's/^/    /' "$log"
  rm -f "$log"
  return 1
}

# ---------------------------------------------------------------------------- helpers
#
# Defined here, above every use. Bash resolves a function at call time, so a helper defined further
# down the file is a "command not found" at whatever line calls it first.

# The last assignment of a key wins, so an operator's appended override is the one that counts.
env_value() {
  sed -n "s/^$1=//p" "$ENV_FILE" 2>/dev/null | tail -1 | sed -e 's/^"//' -e 's/"$//' || true
}

# Rewrites one key in an existing .env, in place, or appends it when it is absent. Used only for the
# proxy settings: they are not secrets, they describe how the host should be reached rather than what
# the database was created with, and the operator has just asked for them. The generated secrets are
# never touched by this, which is the property that makes keeping an existing .env safe.
set_env_key() {
  local key="$1" value="$2"
  if grep -qE "^$key=" "$ENV_FILE"; then
    run sed -i "s|^$key=.*|$key=$value|" "$ENV_FILE"
  else
    run_sh "printf '%s=%s\n' '$key' '$value' >> '$ENV_FILE'"
  fi
}

# Every ${VAR:?...} in the compose file is something the deployment refuses to start without. Read
# the requirement off the compose file instead of repeating it here, so the two cannot drift.
required_keys() {
  grep -oE '\$\{[A-Z_]+:\?' "$INSTALL_DIR/docker-compose.yml" 2>/dev/null \
    | sed -E 's/\$\{([A-Z_]+):\?/\1/' | sort -u || true
}

# The docker group id, without assuming getent is installed.
docker_group_id() {
  if command -v getent >/dev/null 2>&1; then
    getent group docker 2>/dev/null | cut -d: -f3 || true
  else
    grep '^docker:' /etc/group 2>/dev/null | cut -d: -f3 || true
  fi
}

# A best-effort address to put in PUBLIC_URL, which only decides the links the UI shows. `ip` lives
# in iproute2 and is absent from minimal images, so nothing here may be required for the install to
# continue: the fallback is localhost, and --public-url overrides it.
detect_host_ip() {
  local found=""
  if command -v ip >/dev/null 2>&1; then
    found="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}' || true)"
  fi
  if [ -z "$found" ] && command -v hostname >/dev/null 2>&1; then
    found="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  fi
  [ -n "$found" ] || found="localhost"
  printf '%s' "$found"
}

usage() {
  # The header comment is the help text: print it and stop at the first line that is not a comment,
  # so the script body below can never leak into --help.
  awk 'NR > 1 && /^#/ { sub(/^# ?/, ""); print; next } NR > 1 { exit }' "${BASH_SOURCE[0]}"
  exit 0
}

# ---------------------------------------------------------------------------- arguments

# Before parsing, work out whether this script is sitting inside a checkout. If it is, that is the
# directory to install, because it already has an origin remote for the updater to pull.
SCRIPT_PATH="${BASH_SOURCE[0]:-}"
CHECKOUT_DIR=""
if [ -n "$SCRIPT_PATH" ] && [ -f "$SCRIPT_PATH" ]; then
  HERE="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
  if [ -f "$HERE/docker-compose.yml" ] && [ -f "$HERE/server/src/index.ts" ]; then
    CHECKOUT_DIR="$HERE"
  fi
fi
INSTALL_DIR="${CHECKOUT_DIR:-/opt/dockyard}"

while [ $# -gt 0 ]; do
  case "$1" in
    --dir)        [ $# -ge 2 ] || die "--dir needs a path";        INSTALL_DIR="$2"; shift 2 ;;
    --port)       [ $# -ge 2 ] || die "--port needs a number";     PANEL_PORT="$2";  shift 2 ;;
    --bind)       [ $# -ge 2 ] || die "--bind needs an address";   PANEL_BIND="$2"; BIND_SET="yes"; DECIDED="yes"; shift 2 ;;
    --public-url) [ $# -ge 2 ] || die "--public-url needs a URL";  PUBLIC_URL="$2";   shift 2 ;;
    --email)      [ $# -ge 2 ] || die "--email needs an address";  ADMIN_EMAIL="$2"; shift 2 ;;
    --password)   [ $# -ge 2 ] || die "--password needs a value";  ADMIN_PASSWORD="$2"; shift 2 ;;
    --repo)       [ $# -ge 2 ] || die "--repo needs a URL";        REPO_URL="$2";    shift 2 ;;
    --branch)     [ $# -ge 2 ] || die "--branch needs a name";     BRANCH="$2";      shift 2 ;;
    --no-admin)   SET_ADMIN="no"; shift ;;
    --no-updater) INSTALL_UPDATER="no"; shift ;;
    --no-firewall) TOUCH_FIREWALL="no"; shift ;;
    --proxy)      PROXY_ENABLE="yes"; DECIDED="yes"; PROXY_DECIDED="yes"; shift ;;
    --no-proxy)   PROXY_ENABLE="no";  DECIDED="yes"; PROXY_DECIDED="yes"; shift ;;
    --cert)       [ $# -ge 2 ] || die "--cert needs a mode";  CERT_MODE="$2"; CERT_MODE_SET="yes"; DECIDED="yes"; shift 2 ;;
    --domain)     [ $# -ge 2 ] || die "--domain needs a name"; DOMAIN="$2";   DECIDED="yes"; shift 2 ;;
    --http-port)  [ $# -ge 2 ] || die "--http-port needs a number";  PROXY_HTTP_PORT="$2";  DECIDED="yes"; shift 2 ;;
    --https-port) [ $# -ge 2 ] || die "--https-port needs a number"; PROXY_HTTPS_PORT="$2"; DECIDED="yes"; shift 2 ;;
    --tui)        TUI="yes"; shift ;;
    --no-tui)     TUI="no"; shift ;;
    --dry-run)    DRY_RUN="yes"; DECIDED="yes"; shift ;;
    -h|--help)    usage ;;
    *) die "unknown flag: $1 (try --help)" ;;
  esac
done

case "$PANEL_PORT" in
  ''|*[!0-9]*) die "--port must be a number, got '$PANEL_PORT'" ;;
esac

case "$PROXY_HTTP_PORT" in
  ''|*[!0-9]*) die "--http-port must be a number, got '$PROXY_HTTP_PORT'" ;;
esac
case "$PROXY_HTTPS_PORT" in
  ''|*[!0-9]*) die "--https-port must be a number, got '$PROXY_HTTPS_PORT'" ;;
esac

case "$CERT_MODE" in
  self-signed|letsencrypt|none) ;;
  *) die "--cert must be self-signed, letsencrypt or none, got '$CERT_MODE'" ;;
esac

# --proxy on its own means "nginx with TLS", because that is the useful reading and the one a person
# typing it by hand means. Plain HTTP behind nginx is still reachable with an explicit --cert none.
if [ "$PROXY_ENABLE" = "yes" ] && [ "$CERT_MODE_SET" = "no" ] && [ "$DECIDED" = "yes" ]; then
  CERT_MODE="self-signed"
fi

# A certificate needs a name to be issued for. An IP is a legitimate name here (the self-signed path
# puts it in the SAN, and a browser will then match it), so this is only about having *something*.
if [ "$CERT_MODE" != "none" ] && [ -z "$DOMAIN" ] && [ "$DECIDED" = "yes" ]; then
  die "--cert $CERT_MODE needs --domain NAME (a domain, or this host's IP)."
fi

# ---------------------------------------------------------------------------- the interactive setup
#
# Keys are read from /dev/tty, never from stdin, and that is not a detail: under
# `curl -fsSL ... | bash` the script itself is on stdin, so a plain `read` would consume the rest of
# the script instead of a keystroke. Drawing goes to /dev/tty too, so the menus stay out of
# `./install.sh | tee install.log` while the report afterwards still goes to stdout, where a reader
# expects it.
#
# Plain ANSI, with no dependency on whiptail or dialog: this runs on a host that may have no working
# package manager, which is the situation the installer exists for. It uses the alternate screen, so
# it leaves no scrollback behind, and an EXIT trap restores the terminal even if it is interrupted.

TUI_ACTIVE="no"
TUI_CHOICE=0
TUI_TEXT=""
TUI_SECRET="no"
TUI_BOLD=""; TUI_DIM=""; TUI_REV=""; TUI_OFF=""

tui_colours() {
  [ -n "${NO_COLOR:-}" ] && return 0
  TUI_BOLD=$'\033[1m'; TUI_DIM=$'\033[2m'; TUI_REV=$'\033[7m'; TUI_OFF=$'\033[0m'
}

# fd 3 is the terminal for the whole run. No controlling terminal means no TUI, and that is a
# fallback rather than an error: `curl | bash` from cron has nobody to answer a menu.
#
# The probe is a subshell so that a failure is reported to nobody. `exec 3<>/dev/tty 2>/dev/null`
# does not suppress bash's own message, because the shell reports the failed redirection before it
# applies the later ones, and that message would land in the operator's terminal or a captured log.
tui_open() {
  if ! (exec 3<>/dev/tty) 2>/dev/null; then
    return 1
  fi
  exec 3<>/dev/tty
  # The terminal has to be handed back even if the operator interrupts the installer mid-menu, or the
  # shell they land back in is left inside the alternate screen with the cursor hidden.
  trap 'tui_on_exit' EXIT INT TERM
  TUI_ACTIVE="yes"
  return 0
}

tui_close() {
  [ "$TUI_ACTIVE" = "yes" ] || return 0
  printf '\033[?25h\033[?1049l' >&3 2>/dev/null || true
  TUI_ACTIVE="no"
}

# A terminal left inside the alternate screen by a failure is the one thing a TUI must never do.
tui_on_exit() { tui_close; }

tui_begin() {
  printf '\033[?1049h\033[?25l' >&3
}

# One keystroke, as a word: UP DOWN LEFT RIGHT ENTER ESC BACKSPACE, or the character itself.
tui_key() {
  local k a b
  IFS= read -rsn1 -u 3 k || return 1
  case "$k" in
    '') printf 'ENTER' ;;
    $'\x7f'|$'\x08') printf 'BACKSPACE' ;;
    $'\x1b')
      IFS= read -rsn1 -t 0.05 -u 3 a 2>/dev/null || { printf 'ESC'; return 0; }
      IFS= read -rsn1 -t 0.05 -u 3 b 2>/dev/null || b=""
      case "$a$b" in
        '[A') printf 'UP' ;;
        '[B') printf 'DOWN' ;;
        '[C') printf 'RIGHT' ;;
        '[D') printf 'LEFT' ;;
        *) printf 'ESC' ;;
      esac
      ;;
    *) printf '%s' "$k" ;;
  esac
  return 0
}

# Reading can fail (a terminal that has gone away), and an unguarded `key="$(tui_key)"` would then
# trip `set -e` on the assignment itself. ESC is the honest answer: the caller unwinds.
tui_ask_key() {
  local k
  k="$(tui_key)" || k='ESC'
  printf '%s' "$k"
}

tui_screen() {
  printf '\033[2J\033[H' >&3
  printf '\n' >&3
}

tui_title() {
  printf '  %s%s%s\n\n' "$TUI_BOLD" "$1" "$TUI_OFF" >&3
}

tui_text() {
  printf '  %s%s%s\n' "$TUI_DIM" "$1" "$TUI_OFF" >&3
}

tui_footer() {
  printf '\n  %s%s%s\n' "$TUI_DIM" "$1" "$TUI_OFF" >&3
}

# An informational screen. Returns non-zero if the operator backs out.
tui_message() {
  local title="$1" body="$2" key
  while :; do
    tui_screen
    tui_title "$title"
    printf '%s\n' "$body" | while IFS= read -r line; do
      printf '  %s\n' "$line" >&3
    done
    tui_footer "enter continues, q quits"
    key="$(tui_ask_key)"
    case "$key" in
      ENTER) return 0 ;;
      q|Q|ESC) return 1 ;;
    esac
  done
}

# tui_menu TITLE PROMPT DEFAULT_INDEX "label|description"...
# Sets TUI_CHOICE to the chosen index. Non-zero if the operator backs out.
tui_menu() {
  local title="$1" prompt="$2" def="$3"; shift 3
  local -a labels=() descs=()
  local item n sel i key
  for item in "$@"; do
    labels+=("${item%%|*}")
    descs+=("${item#*|}")
  done
  n=${#labels[@]}
  sel="$def"

  while :; do
    tui_screen
    tui_title "$title"
    [ -n "$prompt" ] && printf '  %s\n\n' "$prompt" >&3
    for ((i = 0; i < n; i++)); do
      if [ "$i" -eq "$sel" ]; then
        printf '  %s> %s%s\n' "$TUI_REV" "${labels[$i]}" "$TUI_OFF" >&3
      else
        printf '    %s\n' "${labels[$i]}" >&3
      fi
      [ -n "${descs[$i]}" ] && tui_text "      ${descs[$i]}"
      printf '\n' >&3
    done
    tui_footer "up/down or j/k move, enter selects, q goes back"

    key="$(tui_ask_key)"
    case "$key" in
      UP|k)      sel=$(((sel - 1 + n) % n)) ;;
      DOWN|j)    sel=$(((sel + 1) % n)) ;;
      ENTER|' ') TUI_CHOICE="$sel"; return 0 ;;
      q|Q|ESC)   return 1 ;;
      [1-9])     [ "$key" -le "$n" ] && { TUI_CHOICE=$((key - 1)); return 0; } ;;
    esac
  done
}

# A password typed at this prompt is echoed as asterisks. TUI_SECRET is set by the caller and cleared
# again, so the same widget serves a domain name and a password.
tui_echo() {
  if [ "$TUI_SECRET" = "yes" ]; then
    printf '%s' "$1" | sed 's/./*/g'
  else
    printf '%s' "$1"
  fi
}

# tui_input TITLE PROMPT DEFAULT -> TUI_TEXT. Non-zero if the operator backs out.
tui_input() {
  local title="$1" prompt="$2" def="${3:-}"
  local buf="$def" key
  while :; do
    tui_screen
    tui_title "$title"
    [ -n "$prompt" ] && printf '  %s\n\n' "$prompt" >&3
    printf '  %s>%s %s\n' "$TUI_BOLD" "$TUI_OFF" "$(tui_echo "$buf")" >&3
    tui_footer "enter accepts, backspace deletes, ctrl-c quits"

    key="$(tui_ask_key)"
    case "$key" in
      ENTER)     TUI_TEXT="$buf"; return 0 ;;
      BACKSPACE) buf="${buf%?}" ;;
      UP|DOWN|LEFT|RIGHT|ESC|TAB) : ;;
      ?)         buf="$buf$key" ;;
    esac
  done
}

# ---------------------------------------------------------------------------- the questions

# The last screen before anything is written.
tui_review() {
  local reach cert_line bind_line account
  if [ "$PROXY_ENABLE" = "yes" ]; then
    if [ "$CERT_MODE" = "none" ]; then
      cert_line="no TLS (nginx serves plain HTTP on $PROXY_HTTP_PORT)"
    else
      cert_line="$CERT_MODE certificate for $DOMAIN, on port $PROXY_HTTPS_PORT"
    fi
    reach="nginx on ${PUBLIC_BIND:-0.0.0.0}, forwarding to the panel"
  else
    cert_line="no TLS"
    reach="the panel itself on ${PUBLIC_BIND:-0.0.0.0}:$PANEL_PORT"
  fi
  bind_line="${PUBLIC_BIND:-0.0.0.0}"

  if [ -n "$ADMIN_PASSWORD" ]; then
    account="$ADMIN_EMAIL (with the password you typed)"
  else
    account="$ADMIN_EMAIL (password generated)"
  fi

  tui_message "Ready to install" \
"Here is what will happen.

  reached at     $reach
  listening on   $bind_line
  certificate    $cert_line
  install to     $INSTALL_DIR
  first account  $account

  $([ "$PROXY_ENABLE" = "yes" ] && printf 'The panel moves to 127.0.0.1:%s, so nginx is the only public door.' "$PANEL_PORT" || printf 'The panel is published directly, and it controls Docker.')

Enter installs. q goes back to the questions." 
}

# Walks the choices the installer cannot make for the operator. Sets PROXY_ENABLE, CERT_MODE,
# DOMAIN, the bind addresses, the proxy ports and the first account. The caller owns the terminal:
# fd 3 is already open by the time this runs.
tui_configure() {
  tui_colours
  tui_begin

  tui_message "Dockyard installer" \
"This will install Docker and the Compose plugin, build the panel, start it with
Postgres, and optionally put nginx in front of it with a certificate.

It needs root, and it takes a few minutes on a small host.

Nothing is written until the last screen, so you can back out at any point." || return 1

  # --- how the panel is reached
  tui_menu "How should the panel be reached?" \
"nginx is the only public door, and the panel moves to 127.0.0.1 behind it." 0 \
    "Behind nginx, with TLS|Recommended on a host with a public address. nginx terminates TLS, and the panel stops being published on every interface." \
    "Behind nginx, plain HTTP|For a host where something else already terminates TLS, or that is only reached over a tunnel." \
    "Directly, no proxy|The panel is the door. Plain HTTP, on whatever address you pick next." || return 1
  case "$TUI_CHOICE" in
    0) PROXY_ENABLE="yes"; CERT_MODE="self-signed" ;;
    1) PROXY_ENABLE="yes"; CERT_MODE="none" ;;
    2) PROXY_ENABLE="no";  CERT_MODE="none" ;;
  esac
  PROXY_DECIDED="yes"

  # --- the certificate
  if [ "$CERT_MODE" != "none" ]; then
    tui_menu "What certificate?" \
"A self-signed one works immediately. Let's Encrypt needs a public domain." 0 \
      "Self-signed|Generated now, for the name you give next. Browsers warn until you accept it, which is fine for a panel only you reach." \
      "Let's Encrypt|A certificate every browser trusts. It needs a domain that already points here and port 80 reachable from the internet." || return 1
    case "$TUI_CHOICE" in
      0) CERT_MODE="self-signed" ;;
      1) CERT_MODE="letsencrypt" ;;
    esac

    # --- the name
    if [ "$CERT_MODE" = "letsencrypt" ]; then
      tui_input "The domain" \
"This name must already resolve to this host, and port 80 must be reachable from
the internet, or the certificate authority cannot confirm you own it." "" || return 1
      DOMAIN="$TUI_TEXT"
      if [ -z "$DOMAIN" ]; then
        tui_message "A domain is required" \
"Let's Encrypt will not issue a certificate without a name it can reach this host
on. Go back and either give one, or choose a self-signed certificate instead." || return 1
        return 1
      fi
    else
      tui_input "The name on the certificate" \
"The address you will type to reach the panel. A domain or this host's IP both
work: either goes into the certificate, and either will match." "$(detect_host_ip)" || return 1
      DOMAIN="$TUI_TEXT"
      if [ -z "$DOMAIN" ]; then
        tui_message "A name is required" \
"A certificate is issued for a name. Give the address you will reach the panel on." || return 1
        return 1
      fi
    fi
  fi

  # --- which address the public door listens on
  tui_menu "Which address should it listen on?" \
"This is the address the panel (or nginx, when it is in front) is published on." 0 \
    "All interfaces (0.0.0.0)|Reachable from anywhere this host is reachable from." \
    "Loopback only (127.0.0.1)|Only from this machine. Reach it through a tunnel, an SSH forward, or your own proxy." \
    "A specific address|Type one, for example 10.0.0.5 or a Tailscale address." || return 1
  case "$TUI_CHOICE" in
    0) PUBLIC_BIND="0.0.0.0" ;;
    1) PUBLIC_BIND="127.0.0.1" ;;
    2)
      tui_input "Which address?" "The address to publish on." "$(detect_host_ip)" || return 1
      PUBLIC_BIND="$TUI_TEXT"
      if [ -z "$PUBLIC_BIND" ]; then
        tui_message "An address is required" "Go back and pick one of the first two, or type an address." || return 1
        return 1
      fi
      ;;
  esac

  # --- the ports nginx listens on
  if [ "$PROXY_ENABLE" = "yes" ]; then
    tui_menu "Which ports should nginx use?" \
"These are the host's ports. The panel itself stays on $PANEL_PORT." 0 \
      "The standard ones (80 and 443)|What a browser assumes, and what Let's Encrypt needs." \
      "Different ports|For a host where 80 or 443 is already taken." || return 1
    if [ "$TUI_CHOICE" -eq 1 ]; then
      tui_input "HTTP port" "Plain HTTP. Keep it if you want the redirect to https to work." "8080" || return 1
      PROXY_HTTP_PORT="$TUI_TEXT"
      case "$PROXY_HTTP_PORT" in ''|*[!0-9]*) PROXY_HTTP_PORT="8080" ;; esac
      tui_input "HTTPS port" "The TLS port." "8443" || return 1
      PROXY_HTTPS_PORT="$TUI_TEXT"
      case "$PROXY_HTTPS_PORT" in ''|*[!0-9]*) PROXY_HTTPS_PORT="8443" ;; esac
    fi
  fi

  # --- the first account
  tui_input "The first account" \
"The panel mounts the Docker socket, so whoever can sign in controls this host.
Leave the password blank and one will be generated and shown once at the end." "$ADMIN_EMAIL" || return 1
  [ -n "$TUI_TEXT" ] && ADMIN_EMAIL="$TUI_TEXT"

  TUI_SECRET="yes"
  tui_input "Password for $ADMIN_EMAIL" \
"Leave this blank to have one generated. It is shown once at the end of the
install and written to the config file, which is mode 0600." "" || return 1
  TUI_SECRET="no"
  if [ -n "$TUI_TEXT" ]; then
    ADMIN_PASSWORD="$TUI_TEXT"
  else
    ADMIN_PASSWORD=""
  fi

  # --- the summary
  tui_review || return 1

  tui_close
  return 0
}

# The panel is reached over TLS or it is not, and that single fact decides two settings that must
# agree with each other.
derive_settings() {
  TLS_ON="no"
  if [ "$PROXY_ENABLE" = "yes" ] && [ "$CERT_MODE" != "none" ]; then
    TLS_ON="yes"
  fi

  # The address the operator chose belongs to the public door: nginx when there is one, the panel
  # otherwise. With the proxy on that makes --bind name where nginx publishes, and the panel's own
  # address stops being a choice, because it has to be loopback. Two reasons, both real: the panel
  # port is a Docker-socket door, and with trustProxy on (server/src/app.ts) a directly reachable
  # panel believes whatever X-Forwarded-For it is handed, which walks around the per-IP login limit.
  if [ "$PROXY_ENABLE" = "yes" ]; then
    if [ -n "${PUBLIC_BIND:-}" ]; then
      PROXY_BIND="$PUBLIC_BIND"
    elif [ "$BIND_SET" = "yes" ]; then
      PROXY_BIND="$PANEL_BIND"
    fi
    PANEL_BIND="127.0.0.1"
  elif [ -n "${PUBLIC_BIND:-}" ]; then
    PANEL_BIND="$PUBLIC_BIND"
  fi

  # NODE_ENV and COOKIE_SECURE move together, and the pairing is not a preference. The config layer
  # refuses to boot a production panel with an insecure session cookie (resolveCookieSecure in
  # server/src/config.ts). With TLS the cookie is secure and production is correct. Without TLS a
  # secure cookie is one a browser will not send over http, so sign-in fails in a browser while curl
  # keeps working: that was the bug here, and development is the mode that permits the insecure
  # cookie. It changes nothing else in the server, because config.env is read only by that cookie
  # decision and by the two places that report it.
  if [ "$TLS_ON" = "yes" ]; then
    NODE_ENV_VALUE="production"
    COOKIE_SECURE_VALUE="true"
  else
    NODE_ENV_VALUE="development"
    COOKIE_SECURE_VALUE="false"
  fi

  # PUBLIC_URL is what the panel calls itself in the links it shows, so it has to be the address a
  # person actually types.
  if [ -z "$PUBLIC_URL" ] && [ "$PROXY_ENABLE" = "yes" ]; then
    PROXY_HOST="${DOMAIN:-$(detect_host_ip)}"
    if [ "$TLS_ON" = "yes" ]; then
      PUBLIC_URL="https://$PROXY_HOST"
      [ "$PROXY_HTTPS_PORT" = "443" ] || PUBLIC_URL="$PUBLIC_URL:$PROXY_HTTPS_PORT"
    else
      PUBLIC_URL="http://$PROXY_HOST"
      [ "$PROXY_HTTP_PORT" = "80" ] || PUBLIC_URL="$PUBLIC_URL:$PROXY_HTTP_PORT"
    fi
  fi

  # The compose file gates the nginx service behind the "proxy" profile. Setting COMPOSE_PROFILES in
  # .env rather than passing --profile on every command is deliberate: deploy/update.sh, a manual
  # `docker compose up -d` and the installer's own calls then all agree, and an update cannot
  # silently drop the proxy and republish the panel.
  if [ "$PROXY_ENABLE" = "yes" ]; then
    COMPOSE_PROFILES_VALUE="proxy"
  else
    COMPOSE_PROFILES_VALUE=""
  fi
}

# Runs the setup unless it was switched off, the flags already answered the questions, or there is no
# terminal to draw on.
maybe_run_tui() {
  if [ "$TUI" = "no" ]; then
    say "interactive setup skipped (--no-tui)"
    return 0
  fi
  if [ "$TUI" = "auto" ] && [ "$DECIDED" = "yes" ]; then
    say "flags given, so the interactive setup is skipped"
    return 0
  fi
  if ! tui_open; then
    if [ "$TUI" = "yes" ]; then
      die "--tui needs a terminal, and there is none here."
    fi
    say "no terminal, so the interactive setup is skipped and the defaults are used"
    return 0
  fi
  # tui_open already holds fd 3; hand it to the flow.
  if ! tui_configure; then
    tui_close
    die "cancelled at the setup screen."
  fi
  say "configured through the interactive setup"
}

# ---------------------------------------------------------------------------- preflight

step "Checking the host"
[ "$(id -u)" = "0" ] || die "this needs root, because it installs packages and systemd units. Re-run with sudo."
say "root: ok"

# The questions come after the root check, so a run that cannot proceed fails before it asks
# anything, and before it has written to the terminal.
step "Setup"
maybe_run_tui

# Everything downstream reads these rather than the raw flags: the cookie mode, the node
# environment, the bind addresses and the public URL all follow from the answers above.
derive_settings

PM=""
if command -v apt-get >/dev/null 2>&1; then PM="apt"
elif command -v dnf >/dev/null 2>&1; then PM="dnf"
elif command -v yum >/dev/null 2>&1; then PM="yum"
elif command -v zypper >/dev/null 2>&1; then PM="zypper"
fi
[ -n "$PM" ] || die "no supported package manager found (looked for apt-get, dnf, yum, zypper)."
if [ -r /etc/os-release ]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  say "os:   ${PRETTY_NAME:-unknown}"
fi
say "pkg:  $PM"

# systemd being *installed* is not the same as systemd *running*: in a container `systemctl` exists
# and then refuses with "--now cannot be used when systemd is not running". Ask PID 1 what it is.
if [ "$(cat /proc/1/comm 2>/dev/null)" = "systemd" ] || [ -d /run/systemd/system ]; then
  HAS_SYSTEMD="yes"
else
  HAS_SYSTEMD="no"
fi
say "init: $([ "$HAS_SYSTEMD" = "yes" ] && echo systemd || echo "not systemd (PID 1 is $(cat /proc/1/comm 2>/dev/null || echo unknown))")"

if [ -n "$CHECKOUT_DIR" ] && [ "$INSTALL_DIR" = "$CHECKOUT_DIR" ]; then
  say "mode: installing the checkout this script is in"
else
  say "mode: installing into $INSTALL_DIR"
fi

# ---------------------------------------------------------------------------- packages

step "Installing base packages (ca-certificates, curl, git, openssl)"

install_base_packages() {
  case "$PM" in
    apt)
      run_quiet_sh 'DEBIAN_FRONTEND=noninteractive apt-get update -qq' || return 1
      run_quiet_sh 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq ca-certificates curl git openssl' || return 1
      ;;
    dnf|yum)
      run_quiet "$PM" install -y -q ca-certificates curl git openssl || return 1
      ;;
    zypper)
      run_quiet zypper --non-interactive install ca-certificates curl git openssl || return 1
      ;;
  esac
  return 0
}

# Each step returns explicitly rather than leaning on `set -e`, which is suspended for the body of a
# function called in a condition.
if install_base_packages; then
  [ "$DRY_RUN" = "yes" ] || say "installed"
else
  die "could not install the base packages. Check the network and the package manager output above."
fi

if [ "$DRY_RUN" = "no" ]; then
  for tool in curl git openssl; do
    command -v "$tool" >/dev/null 2>&1 || die "$tool is still missing after the install step."
  done
  say "curl, git, openssl: all present"
fi

# ---------------------------------------------------------------------------- docker

step "Installing Docker Engine and the Compose plugin"

DOCKER_READY="yes"
command -v docker >/dev/null 2>&1 || DOCKER_READY="no"
if [ "$DOCKER_READY" = "yes" ] && docker compose version >/dev/null 2>&1; then
  say "docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo '?') with Compose is already installed"
else
  DOCKER_READY="no"
  say "docker or its Compose plugin is missing; running the official installer"
  # Fetch it to a file and run that, rather than piping straight into a shell, so a truncated or
  # substituted download is caught here instead of halfway through.
  DOCKER_SCRIPT="$(mktemp)"
  if ! run curl -fsSL https://get.docker.com -o "$DOCKER_SCRIPT"; then
    rm -f "$DOCKER_SCRIPT"
    die "could not download https://get.docker.com. Check the network."
  fi
  if [ "$DRY_RUN" = "no" ]; then
    [ -s "$DOCKER_SCRIPT" ] || { rm -f "$DOCKER_SCRIPT"; die "the Docker installer came back empty."; }
    grep -q 'docker' "$DOCKER_SCRIPT" || { rm -f "$DOCKER_SCRIPT"; die "what came back from get.docker.com does not look like the Docker installer."; }
  fi
  if ! run_quiet sh "$DOCKER_SCRIPT"; then
    rm -f "$DOCKER_SCRIPT"
    die "the Docker installer failed. Its output is above."
  fi
  rm -f "$DOCKER_SCRIPT"
  DOCKER_READY="yes"
fi

if [ "$HAS_SYSTEMD" = "yes" ]; then
  # Not fatal: a unit can refuse to start for reasons that have nothing to do with this install, and
  # the daemon check below is the real gate. Failing here would abandon a host that is one step from
  # working.
  if ! run systemctl enable --now docker; then
    warn "could not enable the docker service; will try to start the daemon directly instead."
  fi
fi

if [ "$DRY_RUN" = "no" ]; then
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    COMPOSE=(docker compose)
  elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE=(docker-compose)
  else
    die "Docker installed but neither 'docker compose' nor 'docker-compose' works. Install the Compose plugin and re-run."
  fi
  say "compose: ${COMPOSE[*]}"

  if ! docker info >/dev/null 2>&1; then
    # Nothing has the daemon up: no systemd, or the unit would not start. Starting dockerd directly
    # is the difference between a working panel and a half-install, so try it and say so.
    if command -v dockerd >/dev/null 2>&1; then
      say "the daemon is not up; starting dockerd directly"
      nohup dockerd >/var/log/dockerd.log 2>&1 &
      i=1
      while [ "$i" -le 20 ] && ! docker info >/dev/null 2>&1; do
        i=$((i + 1))
        sleep 1
      done
    fi
  fi

  if ! docker info >/dev/null 2>&1; then
    die "the Docker daemon is not answering. Start it (systemctl start docker, or dockerd) and re-run."
  fi
  say "daemon: answering"
else
  COMPOSE=(docker compose)
fi

# ---------------------------------------------------------------------------- the checkout

step "Preparing the checkout at $INSTALL_DIR"

if [ -f "$INSTALL_DIR/docker-compose.yml" ] && [ -d "$INSTALL_DIR/server/src" ]; then
  say "a checkout is already there; reusing it"
  if [ -d "$INSTALL_DIR/.git" ]; then
    # Only move the checkout when it is clean, and only forwards. Anything else would either lose
    # local work or leave the tree on a commit nobody asked for.
    if git -C "$INSTALL_DIR" diff --quiet && git -C "$INSTALL_DIR" diff --cached --quiet; then
      if run git -C "$INSTALL_DIR" fetch --quiet origin "$BRANCH"; then
        if run git -C "$INSTALL_DIR" merge --ff-only "origin/$BRANCH"; then
          say "moved to $(git -C "$INSTALL_DIR" rev-parse --short HEAD)"
        else
          warn "origin/$BRANCH is not a fast-forward of this checkout, so it was left where it is."
        fi
      else
        warn "could not fetch origin/$BRANCH; building what is on disk."
      fi
    else
      warn "the checkout has uncommitted changes, so it was left alone. Building what is on disk."
    fi
  else
    warn "$INSTALL_DIR is not a git checkout, so the updater will have nothing to pull."
    warn "See deploy/install-updater.sh for how to fix that."
  fi
elif [ -d "$INSTALL_DIR" ] && [ -z "$(ls -A "$INSTALL_DIR" 2>/dev/null)" ]; then
  # An empty directory is what `mkdir /opt/dockyard` leaves behind, and cloning into it works.
  if ! run git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"; then
    die "could not clone $REPO_URL. Check the network and that the repository is reachable."
  fi
  [ "$DRY_RUN" = "yes" ] || say "cloned $REPO_URL ($BRANCH) into the existing empty directory"
elif [ -e "$INSTALL_DIR" ]; then
  die "$INSTALL_DIR exists and is not a Dockyard checkout. Move it aside or pass --dir."
else
  if ! run git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"; then
    die "could not clone $REPO_URL. Check the network and that the repository is reachable."
  fi
  [ "$DRY_RUN" = "yes" ] || say "cloned $REPO_URL ($BRANCH)"
fi

if [ "$DRY_RUN" = "no" ]; then
  [ -f "$INSTALL_DIR/docker-compose.yml" ] || die "$INSTALL_DIR has no docker-compose.yml; that is not the Dockyard repository."
fi

# The Docker socket is root:docker 0660 and the panel image runs as uid/gid 1001, so the panel can
# only open it if it is told the host's docker group id.
DOCKER_GID=""
if [ "$DRY_RUN" = "no" ]; then
  DOCKER_GID="$(docker_group_id)"
  if [ -z "$DOCKER_GID" ]; then
    if grep -q '^docker:' /etc/group 2>/dev/null; then
      die "the docker group exists but has no id, which should not happen. Check 'getent group docker'."
    fi
    command -v groupadd >/dev/null 2>&1 || die "the docker group does not exist and groupadd is not installed, so it cannot be created."
    say "the docker group does not exist yet; creating it"
    run groupadd --system docker
    DOCKER_GID="$(docker_group_id)"
  fi
  [ -n "$DOCKER_GID" ] || die "could not work out the docker group id."
  say "docker group id: $DOCKER_GID"
else
  DOCKER_GID="$(docker_group_id)"
  say "docker group id: ${DOCKER_GID:-<looked up at install time>}"
fi

# ---------------------------------------------------------------------------- the configuration

step "Writing $INSTALL_DIR/.env"

ENV_FILE="$INSTALL_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  say "an .env is already there; keeping it, because its secrets are the ones the database was created with"
  # DOCKER_GID is not a secret and a Docker reinstall can change it, so fill it in when blank.
  if [ -z "$(env_value DOCKER_GID || true)" ] && [ -n "$DOCKER_GID" ]; then
    if grep -qE '^DOCKER_GID=' "$ENV_FILE"; then
      run sed -i "s|^DOCKER_GID=.*|DOCKER_GID=$DOCKER_GID|" "$ENV_FILE"
    else
      run_sh "printf 'DOCKER_GID=%s\n' '$DOCKER_GID' >> '$ENV_FILE'"
    fi
    say "filled in DOCKER_GID=$DOCKER_GID"
  fi
  if [ -n "$ADMIN_PASSWORD" ]; then
    warn "--password was ignored: this .env already exists. Change the password in Settings instead."
  fi

  # The proxy settings are applied to an existing .env rather than left alone, because they are not
  # secrets and because leaving them stale produces the worst kind of failure: the certificate gets
  # minted and the config gets rendered, but nothing starts nginx, so the panel looks proxied and is
  # not. Only done when the proxy was actually chosen on this run.
  if [ "$PROXY_DECIDED" = "yes" ]; then
    set_env_key COMPOSE_PROFILES "$COMPOSE_PROFILES_VALUE"
    set_env_key PROXY_BIND "$PROXY_BIND"
    set_env_key PROXY_HTTP_PORT "$PROXY_HTTP_PORT"
    set_env_key PROXY_HTTPS_PORT "$PROXY_HTTPS_PORT"
    # PANEL_BIND, NODE_ENV and COOKIE_SECURE are not proxy settings as such, but they have to agree
    # with the proxy: the panel has to stop being the public door, and the cookie has to match
    # whether TLS is really on.
    set_env_key PANEL_BIND "$PANEL_BIND"
    set_env_key NODE_ENV "$NODE_ENV_VALUE"
    set_env_key COOKIE_SECURE "$COOKIE_SECURE_VALUE"
    if [ "$PROXY_ENABLE" = "yes" ]; then
      say "applied the proxy settings to the existing .env (nginx on $PROXY_BIND:$PROXY_HTTP_PORT/$PROXY_HTTPS_PORT)"
    else
      say "applied the proxy settings to the existing .env (nginx off, panel back on $PANEL_BIND)"
    fi
  fi
else
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
  SECRET_KEY="$(openssl rand -hex 32)"
  if [ "$SET_ADMIN" = "yes" ] && [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)"
    ADMIN_GENERATED="yes"
  fi
  if [ -z "$PUBLIC_URL" ]; then
    PUBLIC_URL="http://$(detect_host_ip):$PANEL_PORT"
  fi
  ADMIN_LINE="DOCKYARD_ADMIN_EMAIL=$ADMIN_EMAIL"
  if [ "$SET_ADMIN" = "yes" ]; then
    ADMIN_LINE="$ADMIN_LINE
DOCKYARD_ADMIN_PASSWORD=$ADMIN_PASSWORD"
  fi

  write_env_file() {
    # Secrets go in through a heredoc, so they never reach a command line or a temporary file, and
    # the subshell umask keeps the file from ever existing world-readable.
    (
      umask 077
      cat > "$ENV_FILE" <<EOF
# Dockyard configuration, written by install.sh on $(date -u +%FT%TZ).
# .env.example in the repository documents every option, including the ones left at their default.
# This file holds secrets: keep it mode 0600 and never commit it.

# --- The deployment ---
# The panel always listens on 8000 inside its container. This is the host side.
PANEL_PORT=$PANEL_PORT
# Address to publish on. 0.0.0.0 is reachable from anywhere the host is; 127.0.0.1 keeps the panel
# to the host itself, which is what you want when something in front of it does the TLS and the
# authentication. The panel mounts the Docker socket, so this address is a root-equivalent door.
PANEL_BIND=$PANEL_BIND
# What the panel calls itself in the links it shows. Set it to the URL you actually reach it on.
PUBLIC_URL=$PUBLIC_URL
# production behind TLS, development when the panel is served over plain HTTP. This is not a free
# choice: it is tied to the session cookie below, and the config layer refuses to boot a production
# panel with an insecure cookie.
NODE_ENV=$NODE_ENV_VALUE

# --- Postgres ---
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# --- Secrets ---
# Encrypts secrets at rest (AES-256-GCM). Rotating it invalidates stored secrets and nothing else.
SECRET_KEY=$SECRET_KEY

# --- Docker ---
# The panel image runs as uid/gid 1001 and the socket is root:docker 0660, so it needs this to open
# /var/run/docker.sock. It is the host's docker group id, not a password.
DOCKER_GID=$DOCKER_GID

# --- The first account ---
$ADMIN_LINE

# --- Templates ---
# The catalog is not compiled in: it is pulled from this repository, so a template added there
# reaches every install. Set it empty to switch the source off.
DOCKYARD_TEMPLATES_REPO=dockyardapp/dockyard-templates
DOCKYARD_TEMPLATES_BRANCH=main
DOCKYARD_TEMPLATES_REFRESH_MINUTES=15

# --- Version and updates ---
DOCKYARD_UPDATE_REPO=dockyardapp/dockyard
DOCKYARD_UPDATE_BRANCH=$BRANCH
DOCKYARD_UPDATE_ENABLED=true

# --- Sessions ---
SESSION_TTL_HOURS=168
# true when the panel is behind TLS, so the session cookie is only ever sent over https. With it
# false the cookie is not marked Secure, which is the only thing that makes sign-in work over plain
# http, and it is only correct while the panel is not on a public address.
COOKIE_SECURE=$COOKIE_SECURE_VALUE
DOCKYARD_LOGIN_RATE_MAX=10

# --- Reverse proxy ---
# nginx sits in front of the panel and is the only public door. This is what turns it on: the compose
# file gates the nginx service behind the "proxy" profile, and every compose command (here, in
# deploy/update.sh, and typed by hand) reads this file, so an update cannot quietly drop the proxy
# and republish the panel. Set it empty to run without nginx.
COMPOSE_PROFILES=$COMPOSE_PROFILES_VALUE
# The address nginx publishes on, and its ports. The panel keeps PANEL_PORT above and moves to
# 127.0.0.1, so this is the only address that answers from outside.
PROXY_BIND=$PROXY_BIND
PROXY_HTTP_PORT=$PROXY_HTTP_PORT
PROXY_HTTPS_PORT=$PROXY_HTTPS_PORT
EOF
    )
    say "written, mode 0600"
  }

  if [ "$DRY_RUN" = "yes" ]; then
    say "[dry-run] would write $ENV_FILE with generated POSTGRES_PASSWORD and SECRET_KEY"
    say "[dry-run] would write PANEL_PORT=$PANEL_PORT PANEL_BIND=$PANEL_BIND PUBLIC_URL=$PUBLIC_URL DOCKER_GID=${DOCKER_GID:-?}"
  else
    write_env_file
  fi
fi

if [ "$DRY_RUN" = "no" ]; then
  MISSING=""
  for key in $(required_keys); do
    [ -n "$(env_value "$key" || true)" ] || MISSING="$MISSING $key"
  done
  if [ -n "$MISSING" ]; then
    die "$ENV_FILE has no value for:$MISSING
      The compose file refuses to start without them. Add them and re-run."
  fi
  say "every value the compose file requires is set"
fi

# The template directory is read-only for the panel, but the update spool is written by uid 1001.
run mkdir -p "$INSTALL_DIR/data/templates" "$INSTALL_DIR/data/update"
if [ "$DRY_RUN" = "no" ]; then
  # The panel writes the update spool as uid 1001 inside its container, so the directory has to be
  # owned by that uid. A numeric chown works whether or not the host has such a user, and it is the
  # case that matters: a bind-mount source directory Docker creates is owned by root, which the panel
  # cannot write, and the update button then fails with an opaque EACCES.
  if ! chown 1001:1001 "$INSTALL_DIR/data/update" 2>/dev/null; then
    # Only reachable without root. World-writable is worse than it looks here: the host-side updater,
    # which runs as root, trusts what it finds in this directory.
    warn "could not set the owner of data/update to the panel's uid; making it writable instead"
    chmod 0777 "$INSTALL_DIR/data/update"
  fi
  chmod 0755 "$INSTALL_DIR/deploy/update.sh" 2>/dev/null || true
fi

# ---------------------------------------------------------------------------- the proxy

# Where the rendered config and the certificates live. `data/` is in both .gitignore and
# .dockerignore, so none of this is committed and none of it is baked into the image.
NGINX_DIR="$INSTALL_DIR/data/nginx"
NGINX_CERTS="$NGINX_DIR/certs"
NGINX_WWW="$NGINX_DIR/www"
# nginx and the panel are on the same compose network, so the service name resolves. A host-side nginx
# would use 127.0.0.1:8000 instead, which is why the template takes it as a placeholder.
NGINX_UPSTREAM="panel:8000"
NGINX_SERVER_NAME=""
NGINX_CERT_FILE=""
NGINX_KEY_FILE=""
LE_PENDING="no"

# Fills the placeholders the templates carry. A placeholder left behind would be a syntax error
# inside the container, at a point where the cause is no longer visible, so it is checked here.
render_nginx_config() {
  local which="$1" template out
  if [ "$which" = "tls" ]; then
    template="$INSTALL_DIR/deploy/nginx/dockyard-tls.conf.template"
  else
    template="$INSTALL_DIR/deploy/nginx/dockyard-http.conf.template"
  fi
  [ -f "$template" ] || die "the checkout has no $template, so the proxy cannot be configured."

  out="$NGINX_DIR/dockyard.conf"
  sed -e "s|@@SERVER_NAME@@|$NGINX_SERVER_NAME|g" \
      -e "s|@@UPSTREAM@@|$NGINX_UPSTREAM|g" \
      -e "s|@@CERT_FILE@@|$NGINX_CERT_FILE|g" \
      -e "s|@@KEY_FILE@@|$NGINX_KEY_FILE|g" \
      "$template" > "$out.tmp"

  if grep -q '@@[A-Z_]*@@' "$out.tmp"; then
    rm -f "$out.tmp"
    die "a placeholder was left unsubstituted in $(basename "$template"). This is a bug in the installer."
  fi

  # OCSP stapling needs an issuer to ask, and a self-signed certificate has none, so nginx logs
  # `"ssl_stapling" ignored, issuer certificate not found` on every start. It is only a warning, but
  # it is the kind that sends someone looking for a problem that is not there, and the directive
  # cannot do anything useful here.
  if [ "$CERT_MODE" = "self-signed" ]; then
    sed -i 's|^\([[:space:]]*\)\(ssl_stapling[^;]*;\)|\1# \2  # self-signed: no issuer to staple|' "$out.tmp"
  fi

  mv "$out.tmp" "$out"
  say "rendered $(basename "$out") ($which)"
}

# Everything the proxy needs before anything starts. The rendered config has to exist first: it is a
# bind-mount source, and Docker turns a missing bind-mount source into an empty directory, which nginx
# then fails to read as a config.
setup_proxy() {
  [ "$PROXY_ENABLE" = "yes" ] || return 0
  if [ "$DRY_RUN" = "yes" ]; then
    say "[dry-run] would render data/nginx/dockyard.conf and set up a $CERT_MODE certificate"
    return 0
  fi

  step "Setting up nginx"

  run mkdir -p "$NGINX_CERTS" "$NGINX_WWW"
  # nginx serves the ACME challenge from this directory, and certbot writes into it as its own uid, so
  # it cannot be 0700.
  chmod 0755 "$NGINX_WWW"
  # The private key is written 0600 by gen-cert.sh. nginx runs as its own user inside the container and
  # reads the mounted file as root at startup, so the key stays unreadable to anything else on the host.
  chmod 0755 "$NGINX_CERTS"

  NGINX_SERVER_NAME="${DOMAIN:-_}"

  if [ "$TLS_ON" != "yes" ]; then
    render_nginx_config http
    return 0
  fi

  if [ "$CERT_MODE" = "letsencrypt" ]; then
    # The challenge needs this host answering on port 80, which means nginx has to be up first. Start
    # on the HTTP config, then swap in the TLS one once the certificate exists.
    LE_PENDING="yes"
    render_nginx_config http
    say "starting on HTTP so Let's Encrypt can reach the challenge, then switching to TLS"
    return 0
  fi

  GEN="$INSTALL_DIR/deploy/nginx/gen-cert.sh"
  if [ ! -x "$GEN" ]; then
    die "$GEN is missing or not executable, so no certificate can be made. The checkout is incomplete."
  fi

  # gen-cert.sh is idempotent, so a re-run keeps a certificate the browser already trusts, and prints
  # the paths it wrote for the config to use.
  GEN_OUT="$(run "$GEN" "$DOMAIN" "$NGINX_CERTS")" || die "generating a certificate for $DOMAIN failed. The output above says why."
  printf '%s\n' "$GEN_OUT" | head -1 | while IFS= read -r line; do say "$line"; done
  NGINX_CERT_FILE="$(printf '%s\n' "$GEN_OUT" | sed -n 's/^CERT_FILE=//p' | head -1)"
  NGINX_KEY_FILE="$(printf '%s\n' "$GEN_OUT" | sed -n 's/^KEY_FILE=//p' | head -1)"
  if [ -z "$NGINX_CERT_FILE" ] || [ -z "$NGINX_KEY_FILE" ]; then
    die "gen-cert.sh did not report the paths it wrote, so the nginx config cannot be rendered."
  fi

  render_nginx_config tls
}

# Let's Encrypt can only be issued once this host answers on port 80, so it runs after the stack is
# up. certbot is a one-off container rather than a service: it has nothing to do between runs, and a
# restart policy on something that exits would only produce a crash loop.
#
# The layout it writes (certs/live/<name>/fullchain.pem) is certbot's own, and it is the same tree
# nginx already mounts, so a renewal is `certbot renew` plus a reload and nothing here changes.
setup_letsencrypt() {
  [ "$LE_PENDING" = "yes" ] || return 0

  step "Getting a Let's Encrypt certificate for $DOMAIN"

  if ! run docker run --rm \
      -v "$NGINX_CERTS:/etc/letsencrypt" \
      -v "$NGINX_WWW:/var/www/certbot" \
      certbot/certbot certonly --webroot -w /var/www/certbot \
        -d "$DOMAIN" --email "$ADMIN_EMAIL" --agree-tos --no-eff-email \
        --non-interactive --keep-until-expiring; then
    warn "Let's Encrypt could not confirm that $DOMAIN points here."
    warn "That needs the domain to resolve to this host's public address and port 80 to be reachable"
    warn "from the internet. The panel is running on plain HTTP meanwhile, so it is reachable and"
    warn "sign-in works. Re-run with the DNS fixed and the same --proxy --cert letsencrypt --domain,"
    warn "or drop to --cert self-signed to use a certificate that needs no validation."
    die "no certificate was issued, so nginx was left on the plain HTTP config rather than being"
  fi

  NGINX_CERT_FILE="live/$DOMAIN/fullchain.pem"
  NGINX_KEY_FILE="live/$DOMAIN/privkey.pem"
  render_nginx_config tls

  # The config file is bind-mounted read-only, so nginx has to be told to re-read it.
  if ! run "${COMPOSE[@]}" exec -T nginx nginx -s reload; then
    die "nginx would not reload the TLS config. 'cd $INSTALL_DIR && ${COMPOSE[*]} logs nginx' says why."
  fi
  say "nginx is serving TLS for $DOMAIN"
}

setup_proxy

# ---------------------------------------------------------------------------- start it

step "Building and starting the panel"

# Stamped into the image so the panel can name the commit it is running. deploy/update.sh passes
# these too; without them the panel reports the commit as unknown rather than claiming to be current.
GIT_COMMIT=""
if [ "$DRY_RUN" = "no" ]; then
  GIT_COMMIT="$(git -C "$INSTALL_DIR" rev-parse HEAD 2>/dev/null || true)"
fi
BUILD_TIME="$(date -u +%FT%TZ)"
export GIT_COMMIT BUILD_TIME

if [ "$DRY_RUN" = "yes" ]; then
  step "Dry run finished"
  say "Nothing was changed. Re-run without --dry-run to install."
  exit 0
fi

cd "$INSTALL_DIR"
# --build so a re-run picks up a moved checkout. The first run compiles the front end and pulls
# Postgres and the Node base image, so it is minutes on a small host, not seconds.
if ! "${COMPOSE[@]}" up -d --build; then
  die "'${COMPOSE[*]} up -d --build' failed. The output above says why."
fi

# ---------------------------------------------------------------------------- prove it works

step "Waiting for the panel to answer"

HEALTH_URL="http://127.0.0.1:$PANEL_PORT/api/system/health"
ATTEMPTS=90
i=1
HEALTHY="no"
while [ "$i" -le "$ATTEMPTS" ]; do
  if curl -fsS -o /dev/null "$HEALTH_URL" 2>/dev/null; then
    HEALTHY="yes"
    break
  fi
  i=$((i + 1))
  sleep 2
done

if [ "$HEALTHY" != "yes" ]; then
  warn "the panel did not answer $HEALTH_URL within $((ATTEMPTS * 2))s."
  warn "The container is still up, so this may just be a slow first boot."
  "${COMPOSE[@]}" ps
  printf '\n'
  "${COMPOSE[@]}" logs --tail 40 panel
  die "the panel is not answering. The container log is above."
fi
say "answered after about $((i * 2))s"

step "Verifying what it is serving"
INFO="$(curl -fsS "http://127.0.0.1:$PANEL_PORT/api/system/info" 2>/dev/null || true)"
if [ -n "$INFO" ]; then
  # Read the fields out with grep rather than a JSON parser: python3 is not on a minimal host and
  # this is the last thing the install does, so it must not be the step that fails.
  json_str() {
    printf '%s' "$1" | grep -o "\"$2\":\"[^\"]*\"" | head -1 | cut -d'"' -f4 || true
  }
  printf '  %-9s %s\n' "version:" "$(json_str "$INFO" version)"
  printf '  %-9s %s\n' "commit:"  "$(json_str "$INFO" commitShort)"
  printf '  %-9s %s\n' "built:"   "$(json_str "$INFO" builtAt)"
else
  warn "the health endpoint answered but /api/system/info did not."
fi

printf '\n'
"${COMPOSE[@]}" ps

# ---------------------------------------------------------------------------- the proxy, part two

# A Let's Encrypt challenge needs this host answering on port 80, so it could not be issued before the
# stack was up. Nothing happens here unless that mode was chosen.
setup_letsencrypt

# ---------------------------------------------------------------------------- the updater

if [ "$INSTALL_UPDATER" = "yes" ]; then
  step "Installing the host updater"
  if [ "$HAS_SYSTEMD" = "yes" ]; then
    # The panel cannot replace its own image, so it writes a request and a systemd path unit on the
    # host runs deploy/update.sh. Without this the Install update button stays disabled, which is
    # the honest state rather than a button that does nothing.
    if run "$INSTALL_DIR/deploy/install-updater.sh"; then
      say "the panel's Install update button is wired up"
    else
      warn "the updater did not install. The panel will say so and keep the button disabled."
    fi
  else
    warn "no systemd, so the updater was not installed and the Install update button stays disabled."
    warn "Schedule it yourself if you want it: */5 * * * * $INSTALL_DIR/deploy/update.sh"
  fi
else
  step "Skipping the host updater (--no-updater)"
fi

# ---------------------------------------------------------------------------- firewall

if [ "$TOUCH_FIREWALL" = "yes" ]; then
  # Which ports have to be reachable from outside. With the proxy in front the panel is on loopback
  # and nginx is the only door, so opening PANEL_PORT would open nothing useful, and leaving the
  # proxy's ports closed would make the panel unreachable.
  FIREWALL_PORTS=""
  if [ "$PROXY_ENABLE" = "yes" ]; then
    [ "$PROXY_BIND" != "127.0.0.1" ] && FIREWALL_PORTS="$PROXY_HTTP_PORT $PROXY_HTTPS_PORT"
  elif [ "$PANEL_BIND" != "127.0.0.1" ]; then
    FIREWALL_PORTS="$PANEL_PORT"
  fi

  if [ -n "$FIREWALL_PORTS" ] && command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q '^Status: active'; then
    step "Firewall"
    for port in $FIREWALL_PORTS; do
      if ufw status | grep -qE "^$port(/tcp)?\b.*ALLOW"; then
        say "ufw already allows $port"
      else
        run ufw allow "$port/tcp"
        say "ufw: allowed $port/tcp, or nothing outside the host could reach the panel"
      fi
    done
  elif [ -n "$FIREWALL_PORTS" ] && command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
    step "Firewall"
    for port in $FIREWALL_PORTS; do
      run firewall-cmd --permanent --add-port="$port/tcp"
    done
    run firewall-cmd --reload
    say "firewalld: allowed $FIREWALL_PORTS/tcp"
  fi
fi

# ---------------------------------------------------------------------------- done

step "Done"

REACHABLE="$PUBLIC_URL"
[ -n "$REACHABLE" ] || REACHABLE="http://<this host>:$PANEL_PORT"

printf '  %-14s %s\n' "panel" "$REACHABLE"
if [ "$PROXY_ENABLE" = "yes" ]; then
  if [ "$TLS_ON" = "yes" ]; then
    printf '  %-14s %s\n' "proxy" "nginx, TLS with a $CERT_MODE certificate for $DOMAIN"
  else
    printf '  %-14s %s\n' "proxy" "nginx, plain HTTP"
  fi
  printf '  %-14s %s\n' "behind it" "the panel on 127.0.0.1:$PANEL_PORT, not published"
fi
printf '  %-14s %s\n' "checkout" "$INSTALL_DIR"
printf '  %-14s %s\n' "config" "$ENV_FILE  (mode 0600, holds secrets)"
printf '  %-14s %s\n' "logs" "cd $INSTALL_DIR && ${COMPOSE[*]} logs -f panel"
printf '  %-14s %s\n' "update" "cd $INSTALL_DIR && ./deploy/update.sh"

if [ "$SET_ADMIN" = "yes" ]; then
  printf '  %-14s %s\n' "account" "$ADMIN_EMAIL"
  if [ "$ADMIN_GENERATED" = "yes" ]; then
    printf '  %-14s %s\n' "password" "$ADMIN_PASSWORD"
  fi
fi

printf '\n'
if [ "$ADMIN_GENERATED" = "yes" ]; then
  say "That password was generated for this install and is shown once. It is also in $ENV_FILE."
  say "Change it in Settings once you are in."
fi
if [ "$SET_ADMIN" = "no" ]; then
  warn "No admin account was set, so the first person to reach $REACHABLE/login can register as one."
fi
if [ "$PROXY_ENABLE" = "yes" ]; then
  if [ "$TLS_ON" = "no" ]; then
    warn "nginx is serving plain HTTP, so the admin password and the session cookie cross the network"
    warn "in the clear. That is what you want behind a tunnel and it is wrong on an open network:"
    warn "re-run with --proxy --cert self-signed --domain <name> to put TLS in front of it."
  elif [ "$CERT_MODE" = "self-signed" ]; then
    say "The certificate is self-signed, so a browser warns once until you accept it. That is expected,"
    say "and it is the reason the panel's links use $DOMAIN rather than an IP."
  fi
  if [ "$PROXY_BIND" = "0.0.0.0" ]; then
    warn "nginx is published on every interface, and it is the only door to a panel that controls"
    warn "Docker. Treat the certificate and the admin password as things the internet can see."
  fi
elif [ "$PANEL_BIND" = "0.0.0.0" ]; then
  warn "The panel is published on every interface with no proxy in front. It controls Docker, so"
  warn "anyone who reaches it and signs in owns this host. Re-run with --proxy to put nginx in front,"
  warn "or with --bind 127.0.0.1 and let a tunnel or your own proxy be the only way in."
fi
if [ "$PANEL_PORT" = "80" ] && [ "$PROXY_ENABLE" = "no" ]; then
  say "Publishing on 80 is the tunnel case: point a quick or named cloudflared tunnel at 127.0.0.1:80."
fi
printf '\n'
