#!/usr/bin/env bash
# Dockyard installer.
#
# Takes a fresh Linux host to a running panel: Docker Engine with the Compose plugin, git (the
# updater pulls the checkout, so the deployed directory has to be a clone), curl and openssl for the
# generated secrets, then the panel and its Postgres, then the host updater. It finishes by asking
# the panel whether it is up, so a green summary means the API answered, not that a command exited 0.
#
#   curl -fsSL https://raw.githubusercontent.com/dockyardapp/dockyard/main/install.sh | sudo bash
#
# or, from a checkout you already have:
#
#   sudo ./install.sh
#
# Re-running is safe. An existing checkout is reused, an existing .env is never rewritten, and the
# image is rebuilt from whatever the checkout holds.
#
# Flags:
#   --dir PATH          where to install (default: this checkout, else /opt/dockyard)
#   --port N            host port to publish the panel on (default 8000)
#   --bind ADDR         address to publish on (default 0.0.0.0; 127.0.0.1 keeps it on the host)
#   --public-url URL    the URL the panel will be reached at, used for the links it shows
#   --email ADDR        admin account email (default admin@dockyard.local)
#   --password PASS     admin password (generated and shown once if you do not pass one)
#   --no-admin          leave the admin account unset and register it in the UI instead
#   --repo URL          repository to clone (default the public Dockyard repository)
#   --branch NAME       branch to install (default main)
#   --no-updater        skip the host updater; the Install update button stays disabled
#   --no-firewall       never touch the firewall, only report what it would need
#   --dry-run           print what would happen and change nothing
#   -h, --help          this
#
# Why an admin password is generated by default: the panel mounts the Docker socket, so anyone who
# can sign in has root-equivalent control of the host. The user table is empty until an account
# exists, and while it is empty the bootstrap route is open, so an install published on a public
# address with no password set is a race that whoever finds the port first wins. Generating one
# closes that window. Pass --no-admin to take the race deliberately.
set -Eeuo pipefail

DEFAULT_REPO_URL="https://github.com/dockyardapp/dockyard.git"
DEFAULT_EMAIL="admin@dockyard.local"

INSTALL_DIR=""
PANEL_PORT="8000"
PANEL_BIND="0.0.0.0"
PUBLIC_URL=""
ADMIN_EMAIL="$DEFAULT_EMAIL"
ADMIN_PASSWORD=""
ADMIN_GENERATED="no"
REPO_URL="$DEFAULT_REPO_URL"
BRANCH="main"
INSTALL_UPDATER="yes"
SET_ADMIN="yes"
TOUCH_FIREWALL="yes"
DRY_RUN="no"
COMPOSE=()

say()  { printf '  %s\n' "$*"; }
step() { printf '\n%s\n' "$*"; }
# Warnings go to stdout with the rest of the report, not to stderr. This script's output is a
# document a person reads top to bottom, and splitting it across two streams means `./install.sh |
# tee install.log` shows every warning before the step it belongs to.
warn() { printf '  ! %s\n' "$*"; }
die()  { printf '\n  x %s\n\n' "$*" >&2; exit 1; }

# Mutating commands go through these, so --dry-run has exactly one meaning: nothing changes.
run() {
  if [ "$DRY_RUN" = "yes" ]; then
    printf '  [dry-run] %s\n' "$*"
    return 0
  fi
  "$@"
}
run_sh() {
  if [ "$DRY_RUN" = "yes" ]; then
    printf '  [dry-run] sh -c %s\n' "$1"
    return 0
  fi
  sh -c "$1"
}

# For steps whose output is loud and uninteresting: a package manager unpacking a hundred
# dependencies buries the report this script exists to print. Capture it and surface it only when the
# step fails, so a failure is still fully explained.
run_quiet() {
  if [ "$DRY_RUN" = "yes" ]; then
    printf '  [dry-run] %s\n' "$*"
    return 0
  fi
  local log
  log="$(mktemp)"
  if "$@" >"$log" 2>&1; then
    rm -f "$log"
    return 0
  fi
  printf '  step failed: %s\n' "$*"
  sed 's/^/    /' "$log"
  rm -f "$log"
  return 1
}
run_quiet_sh() {
  if [ "$DRY_RUN" = "yes" ]; then
    printf '  [dry-run] sh -c %s\n' "$1"
    return 0
  fi
  local log
  log="$(mktemp)"
  if sh -c "$1" >"$log" 2>&1; then
    rm -f "$log"
    return 0
  fi
  printf '  step failed: sh -c %s\n' "$1"
  sed 's/^/    /' "$log"
  rm -f "$log"
  return 1
}

# ---------------------------------------------------------------------------- helpers
#
# Defined here, above every use. Bash resolves a function at call time, so a helper defined further
# down the file is a "command not found" at whatever line calls it first.

# The last assignment of a key wins, so an operator's appended override is the one that counts.
env_value() {
  sed -n "s/^$1=//p" "$ENV_FILE" 2>/dev/null | tail -1 | sed -e 's/^"//' -e 's/"$//' || true
}

# Every ${VAR:?...} in the compose file is something the deployment refuses to start without. Read
# the requirement off the compose file instead of repeating it here, so the two cannot drift.
required_keys() {
  grep -oE '\$\{[A-Z_]+:\?' "$INSTALL_DIR/docker-compose.yml" 2>/dev/null \
    | sed -E 's/\$\{([A-Z_]+):\?/\1/' | sort -u || true
}

# The docker group id, without assuming getent is installed.
docker_group_id() {
  if command -v getent >/dev/null 2>&1; then
    getent group docker 2>/dev/null | cut -d: -f3 || true
  else
    grep '^docker:' /etc/group 2>/dev/null | cut -d: -f3 || true
  fi
}

# A best-effort address to put in PUBLIC_URL, which only decides the links the UI shows. `ip` lives
# in iproute2 and is absent from minimal images, so nothing here may be required for the install to
# continue: the fallback is localhost, and --public-url overrides it.
detect_host_ip() {
  local found=""
  if command -v ip >/dev/null 2>&1; then
    found="$(ip -4 route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}' || true)"
  fi
  if [ -z "$found" ] && command -v hostname >/dev/null 2>&1; then
    found="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  fi
  [ -n "$found" ] || found="localhost"
  printf '%s' "$found"
}

usage() {
  # The header comment is the help text: print it and stop at the first line that is not a comment,
  # so the script body below can never leak into --help.
  awk 'NR > 1 && /^#/ { sub(/^# ?/, ""); print; next } NR > 1 { exit }' "${BASH_SOURCE[0]}"
  exit 0
}

# ---------------------------------------------------------------------------- arguments

# Before parsing, work out whether this script is sitting inside a checkout. If it is, that is the
# directory to install, because it already has an origin remote for the updater to pull.
SCRIPT_PATH="${BASH_SOURCE[0]:-}"
CHECKOUT_DIR=""
if [ -n "$SCRIPT_PATH" ] && [ -f "$SCRIPT_PATH" ]; then
  HERE="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
  if [ -f "$HERE/docker-compose.yml" ] && [ -f "$HERE/server/src/index.ts" ]; then
    CHECKOUT_DIR="$HERE"
  fi
fi
INSTALL_DIR="${CHECKOUT_DIR:-/opt/dockyard}"

while [ $# -gt 0 ]; do
  case "$1" in
    --dir)        [ $# -ge 2 ] || die "--dir needs a path";        INSTALL_DIR="$2"; shift 2 ;;
    --port)       [ $# -ge 2 ] || die "--port needs a number";     PANEL_PORT="$2";  shift 2 ;;
    --bind)       [ $# -ge 2 ] || die "--bind needs an address";   PANEL_BIND="$2";  shift 2 ;;
    --public-url) [ $# -ge 2 ] || die "--public-url needs a URL";  PUBLIC_URL="$2";   shift 2 ;;
    --email)      [ $# -ge 2 ] || die "--email needs an address";  ADMIN_EMAIL="$2"; shift 2 ;;
    --password)   [ $# -ge 2 ] || die "--password needs a value";  ADMIN_PASSWORD="$2"; shift 2 ;;
    --repo)       [ $# -ge 2 ] || die "--repo needs a URL";        REPO_URL="$2";    shift 2 ;;
    --branch)     [ $# -ge 2 ] || die "--branch needs a name";     BRANCH="$2";      shift 2 ;;
    --no-admin)   SET_ADMIN="no"; shift ;;
    --no-updater) INSTALL_UPDATER="no"; shift ;;
    --no-firewall) TOUCH_FIREWALL="no"; shift ;;
    --dry-run)    DRY_RUN="yes"; shift ;;
    -h|--help)    usage ;;
    *) die "unknown flag: $1 (try --help)" ;;
  esac
done

case "$PANEL_PORT" in
  ''|*[!0-9]*) die "--port must be a number, got '$PANEL_PORT'" ;;
esac

# ---------------------------------------------------------------------------- preflight

step "Checking the host"
[ "$(id -u)" = "0" ] || die "this needs root, because it installs packages and systemd units. Re-run with sudo."
say "root: ok"

PM=""
if command -v apt-get >/dev/null 2>&1; then PM="apt"
elif command -v dnf >/dev/null 2>&1; then PM="dnf"
elif command -v yum >/dev/null 2>&1; then PM="yum"
elif command -v zypper >/dev/null 2>&1; then PM="zypper"
fi
[ -n "$PM" ] || die "no supported package manager found (looked for apt-get, dnf, yum, zypper)."
if [ -r /etc/os-release ]; then
  # shellcheck disable=SC1091
  . /etc/os-release
  say "os:   ${PRETTY_NAME:-unknown}"
fi
say "pkg:  $PM"

# systemd being *installed* is not the same as systemd *running*: in a container `systemctl` exists
# and then refuses with "--now cannot be used when systemd is not running". Ask PID 1 what it is.
if [ "$(cat /proc/1/comm 2>/dev/null)" = "systemd" ] || [ -d /run/systemd/system ]; then
  HAS_SYSTEMD="yes"
else
  HAS_SYSTEMD="no"
fi
say "init: $([ "$HAS_SYSTEMD" = "yes" ] && echo systemd || echo "not systemd (PID 1 is $(cat /proc/1/comm 2>/dev/null || echo unknown))")"

if [ -n "$CHECKOUT_DIR" ] && [ "$INSTALL_DIR" = "$CHECKOUT_DIR" ]; then
  say "mode: installing the checkout this script is in"
else
  say "mode: installing into $INSTALL_DIR"
fi

# ---------------------------------------------------------------------------- packages

step "Installing base packages (ca-certificates, curl, git, openssl)"

install_base_packages() {
  case "$PM" in
    apt)
      run_quiet_sh 'DEBIAN_FRONTEND=noninteractive apt-get update -qq' || return 1
      run_quiet_sh 'DEBIAN_FRONTEND=noninteractive apt-get install -y -qq ca-certificates curl git openssl' || return 1
      ;;
    dnf|yum)
      run_quiet "$PM" install -y -q ca-certificates curl git openssl || return 1
      ;;
    zypper)
      run_quiet zypper --non-interactive install ca-certificates curl git openssl || return 1
      ;;
  esac
  return 0
}

# Each step returns explicitly rather than leaning on `set -e`, which is suspended for the body of a
# function called in a condition.
if install_base_packages; then
  [ "$DRY_RUN" = "yes" ] || say "installed"
else
  die "could not install the base packages. Check the network and the package manager output above."
fi

if [ "$DRY_RUN" = "no" ]; then
  for tool in curl git openssl; do
    command -v "$tool" >/dev/null 2>&1 || die "$tool is still missing after the install step."
  done
  say "curl, git, openssl: all present"
fi

# ---------------------------------------------------------------------------- docker

step "Installing Docker Engine and the Compose plugin"

DOCKER_READY="yes"
command -v docker >/dev/null 2>&1 || DOCKER_READY="no"
if [ "$DOCKER_READY" = "yes" ] && docker compose version >/dev/null 2>&1; then
  say "docker $(docker version --format '{{.Server.Version}}' 2>/dev/null || echo '?') with Compose is already installed"
else
  DOCKER_READY="no"
  say "docker or its Compose plugin is missing; running the official installer"
  # Fetch it to a file and run that, rather than piping straight into a shell, so a truncated or
  # substituted download is caught here instead of halfway through.
  DOCKER_SCRIPT="$(mktemp)"
  if ! run curl -fsSL https://get.docker.com -o "$DOCKER_SCRIPT"; then
    rm -f "$DOCKER_SCRIPT"
    die "could not download https://get.docker.com. Check the network."
  fi
  if [ "$DRY_RUN" = "no" ]; then
    [ -s "$DOCKER_SCRIPT" ] || { rm -f "$DOCKER_SCRIPT"; die "the Docker installer came back empty."; }
    grep -q 'docker' "$DOCKER_SCRIPT" || { rm -f "$DOCKER_SCRIPT"; die "what came back from get.docker.com does not look like the Docker installer."; }
  fi
  if ! run_quiet sh "$DOCKER_SCRIPT"; then
    rm -f "$DOCKER_SCRIPT"
    die "the Docker installer failed. Its output is above."
  fi
  rm -f "$DOCKER_SCRIPT"
  DOCKER_READY="yes"
fi

if [ "$HAS_SYSTEMD" = "yes" ]; then
  # Not fatal: a unit can refuse to start for reasons that have nothing to do with this install, and
  # the daemon check below is the real gate. Failing here would abandon a host that is one step from
  # working.
  if ! run systemctl enable --now docker; then
    warn "could not enable the docker service; will try to start the daemon directly instead."
  fi
fi

if [ "$DRY_RUN" = "no" ]; then
  if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    COMPOSE=(docker compose)
  elif command -v docker-compose >/dev/null 2>&1; then
    COMPOSE=(docker-compose)
  else
    die "Docker installed but neither 'docker compose' nor 'docker-compose' works. Install the Compose plugin and re-run."
  fi
  say "compose: ${COMPOSE[*]}"

  if ! docker info >/dev/null 2>&1; then
    # Nothing has the daemon up: no systemd, or the unit would not start. Starting dockerd directly
    # is the difference between a working panel and a half-install, so try it and say so.
    if command -v dockerd >/dev/null 2>&1; then
      say "the daemon is not up; starting dockerd directly"
      nohup dockerd >/var/log/dockerd.log 2>&1 &
      i=1
      while [ "$i" -le 20 ] && ! docker info >/dev/null 2>&1; do
        i=$((i + 1))
        sleep 1
      done
    fi
  fi

  if ! docker info >/dev/null 2>&1; then
    die "the Docker daemon is not answering. Start it (systemctl start docker, or dockerd) and re-run."
  fi
  say "daemon: answering"
else
  COMPOSE=(docker compose)
fi

# ---------------------------------------------------------------------------- the checkout

step "Preparing the checkout at $INSTALL_DIR"

if [ -f "$INSTALL_DIR/docker-compose.yml" ] && [ -d "$INSTALL_DIR/server/src" ]; then
  say "a checkout is already there; reusing it"
  if [ -d "$INSTALL_DIR/.git" ]; then
    # Only move the checkout when it is clean, and only forwards. Anything else would either lose
    # local work or leave the tree on a commit nobody asked for.
    if git -C "$INSTALL_DIR" diff --quiet && git -C "$INSTALL_DIR" diff --cached --quiet; then
      if run git -C "$INSTALL_DIR" fetch --quiet origin "$BRANCH"; then
        if run git -C "$INSTALL_DIR" merge --ff-only "origin/$BRANCH"; then
          say "moved to $(git -C "$INSTALL_DIR" rev-parse --short HEAD)"
        else
          warn "origin/$BRANCH is not a fast-forward of this checkout, so it was left where it is."
        fi
      else
        warn "could not fetch origin/$BRANCH; building what is on disk."
      fi
    else
      warn "the checkout has uncommitted changes, so it was left alone. Building what is on disk."
    fi
  else
    warn "$INSTALL_DIR is not a git checkout, so the updater will have nothing to pull."
    warn "See deploy/install-updater.sh for how to fix that."
  fi
elif [ -d "$INSTALL_DIR" ] && [ -z "$(ls -A "$INSTALL_DIR" 2>/dev/null)" ]; then
  # An empty directory is what `mkdir /opt/dockyard` leaves behind, and cloning into it works.
  if ! run git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"; then
    die "could not clone $REPO_URL. Check the network and that the repository is reachable."
  fi
  [ "$DRY_RUN" = "yes" ] || say "cloned $REPO_URL ($BRANCH) into the existing empty directory"
elif [ -e "$INSTALL_DIR" ]; then
  die "$INSTALL_DIR exists and is not a Dockyard checkout. Move it aside or pass --dir."
else
  if ! run git clone --branch "$BRANCH" --depth 1 "$REPO_URL" "$INSTALL_DIR"; then
    die "could not clone $REPO_URL. Check the network and that the repository is reachable."
  fi
  [ "$DRY_RUN" = "yes" ] || say "cloned $REPO_URL ($BRANCH)"
fi

if [ "$DRY_RUN" = "no" ]; then
  [ -f "$INSTALL_DIR/docker-compose.yml" ] || die "$INSTALL_DIR has no docker-compose.yml; that is not the Dockyard repository."
fi

# The Docker socket is root:docker 0660 and the panel image runs as uid/gid 1001, so the panel can
# only open it if it is told the host's docker group id.
DOCKER_GID=""
if [ "$DRY_RUN" = "no" ]; then
  DOCKER_GID="$(docker_group_id)"
  if [ -z "$DOCKER_GID" ]; then
    if grep -q '^docker:' /etc/group 2>/dev/null; then
      die "the docker group exists but has no id, which should not happen. Check 'getent group docker'."
    fi
    command -v groupadd >/dev/null 2>&1 || die "the docker group does not exist and groupadd is not installed, so it cannot be created."
    say "the docker group does not exist yet; creating it"
    run groupadd --system docker
    DOCKER_GID="$(docker_group_id)"
  fi
  [ -n "$DOCKER_GID" ] || die "could not work out the docker group id."
  say "docker group id: $DOCKER_GID"
else
  DOCKER_GID="$(docker_group_id)"
  say "docker group id: ${DOCKER_GID:-<looked up at install time>}"
fi

# ---------------------------------------------------------------------------- the configuration

step "Writing $INSTALL_DIR/.env"

ENV_FILE="$INSTALL_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  say "an .env is already there; keeping it, because its secrets are the ones the database was created with"
  # DOCKER_GID is not a secret and a Docker reinstall can change it, so fill it in when blank.
  if [ -z "$(env_value DOCKER_GID || true)" ] && [ -n "$DOCKER_GID" ]; then
    if grep -qE '^DOCKER_GID=' "$ENV_FILE"; then
      run sed -i "s|^DOCKER_GID=.*|DOCKER_GID=$DOCKER_GID|" "$ENV_FILE"
    else
      run_sh "printf 'DOCKER_GID=%s\n' '$DOCKER_GID' >> '$ENV_FILE'"
    fi
    say "filled in DOCKER_GID=$DOCKER_GID"
  fi
  if [ -n "$ADMIN_PASSWORD" ]; then
    warn "--password was ignored: this .env already exists. Change the password in Settings instead."
  fi
else
  POSTGRES_PASSWORD="$(openssl rand -hex 24)"
  SECRET_KEY="$(openssl rand -hex 32)"
  if [ "$SET_ADMIN" = "yes" ] && [ -z "$ADMIN_PASSWORD" ]; then
    ADMIN_PASSWORD="$(openssl rand -base64 18 | tr -d '/+=' | cut -c1-20)"
    ADMIN_GENERATED="yes"
  fi
  if [ -z "$PUBLIC_URL" ]; then
    PUBLIC_URL="http://$(detect_host_ip):$PANEL_PORT"
  fi
  ADMIN_LINE="DOCKYARD_ADMIN_EMAIL=$ADMIN_EMAIL"
  if [ "$SET_ADMIN" = "yes" ]; then
    ADMIN_LINE="$ADMIN_LINE
DOCKYARD_ADMIN_PASSWORD=$ADMIN_PASSWORD"
  fi

  write_env_file() {
    # Secrets go in through a heredoc, so they never reach a command line or a temporary file, and
    # the subshell umask keeps the file from ever existing world-readable.
    (
      umask 077
      cat > "$ENV_FILE" <<EOF
# Dockyard configuration, written by install.sh on $(date -u +%FT%TZ).
# .env.example in the repository documents every option, including the ones left at their default.
# This file holds secrets: keep it mode 0600 and never commit it.

# --- The deployment ---
# The panel always listens on 8000 inside its container. This is the host side.
PANEL_PORT=$PANEL_PORT
# Address to publish on. 0.0.0.0 is reachable from anywhere the host is; 127.0.0.1 keeps the panel
# to the host itself, which is what you want when something in front of it does the TLS and the
# authentication. The panel mounts the Docker socket, so this address is a root-equivalent door.
PANEL_BIND=$PANEL_BIND
# What the panel calls itself in the links it shows. Set it to the URL you actually reach it on.
PUBLIC_URL=$PUBLIC_URL
NODE_ENV=production

# --- Postgres ---
POSTGRES_PASSWORD=$POSTGRES_PASSWORD

# --- Secrets ---
# Encrypts secrets at rest (AES-256-GCM). Rotating it invalidates stored secrets and nothing else.
SECRET_KEY=$SECRET_KEY

# --- Docker ---
# The panel image runs as uid/gid 1001 and the socket is root:docker 0660, so it needs this to open
# /var/run/docker.sock. It is the host's docker group id, not a password.
DOCKER_GID=$DOCKER_GID

# --- The first account ---
$ADMIN_LINE

# --- Templates ---
# The catalog is not compiled in: it is pulled from this repository, so a template added there
# reaches every install. Set it empty to switch the source off.
DOCKYARD_TEMPLATES_REPO=dockyardapp/dockyard-templates
DOCKYARD_TEMPLATES_BRANCH=main
DOCKYARD_TEMPLATES_REFRESH_MINUTES=15

# --- Version and updates ---
DOCKYARD_UPDATE_REPO=dockyardapp/dockyard
DOCKYARD_UPDATE_BRANCH=$BRANCH
DOCKYARD_UPDATE_ENABLED=true

# --- Sessions ---
SESSION_TTL_HOURS=168
# Set to true once the panel is behind TLS, so the session cookie is only ever sent over https.
COOKIE_SECURE=false
DOCKYARD_LOGIN_RATE_MAX=10
EOF
    )
    say "written, mode 0600"
  }

  if [ "$DRY_RUN" = "yes" ]; then
    say "[dry-run] would write $ENV_FILE with generated POSTGRES_PASSWORD and SECRET_KEY"
    say "[dry-run] would write PANEL_PORT=$PANEL_PORT PANEL_BIND=$PANEL_BIND PUBLIC_URL=$PUBLIC_URL DOCKER_GID=${DOCKER_GID:-?}"
  else
    write_env_file
  fi
fi

if [ "$DRY_RUN" = "no" ]; then
  MISSING=""
  for key in $(required_keys); do
    [ -n "$(env_value "$key" || true)" ] || MISSING="$MISSING $key"
  done
  if [ -n "$MISSING" ]; then
    die "$ENV_FILE has no value for:$MISSING
      The compose file refuses to start without them. Add them and re-run."
  fi
  say "every value the compose file requires is set"
fi

# The template directory is read-only for the panel, but the update spool is written by uid 1001.
run mkdir -p "$INSTALL_DIR/data/templates" "$INSTALL_DIR/data/update"
if [ "$DRY_RUN" = "no" ]; then
  if getent passwd 1001 >/dev/null 2>&1; then
    chown 1001:1001 "$INSTALL_DIR/data/update" 2>/dev/null || true
  else
    # No such local user: the uid only exists inside the image, so fall back to group write.
    chmod 0777 "$INSTALL_DIR/data/update"
  fi
  chmod 0755 "$INSTALL_DIR/deploy/update.sh" 2>/dev/null || true
fi

# ---------------------------------------------------------------------------- start it

step "Building and starting the panel"

# Stamped into the image so the panel can name the commit it is running. deploy/update.sh passes
# these too; without them the panel reports the commit as unknown rather than claiming to be current.
GIT_COMMIT=""
if [ "$DRY_RUN" = "no" ]; then
  GIT_COMMIT="$(git -C "$INSTALL_DIR" rev-parse HEAD 2>/dev/null || true)"
fi
BUILD_TIME="$(date -u +%FT%TZ)"
export GIT_COMMIT BUILD_TIME

if [ "$DRY_RUN" = "yes" ]; then
  step "Dry run finished"
  say "Nothing was changed. Re-run without --dry-run to install."
  exit 0
fi

cd "$INSTALL_DIR"
# --build so a re-run picks up a moved checkout. The first run compiles the front end and pulls
# Postgres and the Node base image, so it is minutes on a small host, not seconds.
if ! "${COMPOSE[@]}" up -d --build; then
  die "'${COMPOSE[*]} up -d --build' failed. The output above says why."
fi

# ---------------------------------------------------------------------------- prove it works

step "Waiting for the panel to answer"

HEALTH_URL="http://127.0.0.1:$PANEL_PORT/api/system/health"
ATTEMPTS=90
i=1
HEALTHY="no"
while [ "$i" -le "$ATTEMPTS" ]; do
  if curl -fsS -o /dev/null "$HEALTH_URL" 2>/dev/null; then
    HEALTHY="yes"
    break
  fi
  i=$((i + 1))
  sleep 2
done

if [ "$HEALTHY" != "yes" ]; then
  warn "the panel did not answer $HEALTH_URL within $((ATTEMPTS * 2))s."
  warn "The container is still up, so this may just be a slow first boot."
  "${COMPOSE[@]}" ps
  printf '\n'
  "${COMPOSE[@]}" logs --tail 40 panel
  die "the panel is not answering. The container log is above."
fi
say "answered after about $((i * 2))s"

step "Verifying what it is serving"
INFO="$(curl -fsS "http://127.0.0.1:$PANEL_PORT/api/system/info" 2>/dev/null || true)"
if [ -n "$INFO" ]; then
  # Read the fields out with grep rather than a JSON parser: python3 is not on a minimal host and
  # this is the last thing the install does, so it must not be the step that fails.
  json_str() {
    printf '%s' "$1" | grep -o "\"$2\":\"[^\"]*\"" | head -1 | cut -d'"' -f4 || true
  }
  printf '  %-9s %s\n' "version:" "$(json_str "$INFO" version)"
  printf '  %-9s %s\n' "commit:"  "$(json_str "$INFO" commitShort)"
  printf '  %-9s %s\n' "built:"   "$(json_str "$INFO" builtAt)"
else
  warn "the health endpoint answered but /api/system/info did not."
fi

printf '\n'
"${COMPOSE[@]}" ps

# ---------------------------------------------------------------------------- the updater

if [ "$INSTALL_UPDATER" = "yes" ]; then
  step "Installing the host updater"
  if [ "$HAS_SYSTEMD" = "yes" ]; then
    # The panel cannot replace its own image, so it writes a request and a systemd path unit on the
    # host runs deploy/update.sh. Without this the Install update button stays disabled, which is
    # the honest state rather than a button that does nothing.
    if run "$INSTALL_DIR/deploy/install-updater.sh"; then
      say "the panel's Install update button is wired up"
    else
      warn "the updater did not install. The panel will say so and keep the button disabled."
    fi
  else
    warn "no systemd, so the updater was not installed and the Install update button stays disabled."
    warn "Schedule it yourself if you want it: */5 * * * * $INSTALL_DIR/deploy/update.sh"
  fi
else
  step "Skipping the host updater (--no-updater)"
fi

# ---------------------------------------------------------------------------- firewall

if [ "$TOUCH_FIREWALL" = "yes" ] && [ "$PANEL_BIND" != "127.0.0.1" ]; then
  if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q '^Status: active'; then
    step "Firewall"
    if ufw status | grep -qE "^$PANEL_PORT(/tcp)?\b.*ALLOW"; then
      say "ufw already allows $PANEL_PORT"
    else
      run ufw allow "$PANEL_PORT/tcp"
      say "ufw: allowed $PANEL_PORT/tcp, or nothing outside the host could reach the panel"
    fi
  elif command -v firewall-cmd >/dev/null 2>&1 && firewall-cmd --state >/dev/null 2>&1; then
    step "Firewall"
    run firewall-cmd --permanent --add-port="$PANEL_PORT/tcp"
    run firewall-cmd --reload
    say "firewalld: allowed $PANEL_PORT/tcp"
  fi
fi

# ---------------------------------------------------------------------------- done

step "Done"

REACHABLE="$PUBLIC_URL"
[ -n "$REACHABLE" ] || REACHABLE="http://<this host>:$PANEL_PORT"

printf '  %-14s %s\n' "panel" "$REACHABLE"
printf '  %-14s %s\n' "checkout" "$INSTALL_DIR"
printf '  %-14s %s\n' "config" "$ENV_FILE  (mode 0600, holds secrets)"
printf '  %-14s %s\n' "logs" "cd $INSTALL_DIR && ${COMPOSE[*]} logs -f panel"
printf '  %-14s %s\n' "update" "cd $INSTALL_DIR && ./deploy/update.sh"

if [ "$SET_ADMIN" = "yes" ]; then
  printf '  %-14s %s\n' "account" "$ADMIN_EMAIL"
  if [ "$ADMIN_GENERATED" = "yes" ]; then
    printf '  %-14s %s\n' "password" "$ADMIN_PASSWORD"
  fi
fi

printf '\n'
if [ "$ADMIN_GENERATED" = "yes" ]; then
  say "That password was generated for this install and is shown once. It is also in $ENV_FILE."
  say "Change it in Settings once you are in."
fi
if [ "$SET_ADMIN" = "no" ]; then
  warn "No admin account was set, so the first person to reach $REACHABLE/login can register as one."
fi
if [ "$PANEL_BIND" = "0.0.0.0" ]; then
  warn "The panel is published on every interface. It controls Docker, so anyone who reaches it"
  warn "and signs in owns this host. Put TLS and authentication in front before exposing it, or"
  warn "re-run with --bind 127.0.0.1 and let a tunnel or a proxy be the only way in."
fi
if [ "$PANEL_PORT" = "80" ]; then
  say "Publishing on 80 is the tunnel case: point a quick or named cloudflared tunnel at 127.0.0.1:80."
fi
printf '\n'
